In [1]:
-- Gloria Budiman
-- EE569 HW4
-- 6528-1836-50
-- 11/25/2016

require 'nn'
require 'optim'

torch.manualSeed(0)
torch.setnumthreads(4)

In [2]:
function setup() 
    classes = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }
    geometry = { 32, 32 }

    net = nn.Sequential()

    net:add(nn.SpatialConvolution(1, 6, 5, 5))
    net:add(nn.ReLU())
    net:add(nn.SpatialMaxPooling(2, 2, 2, 2))

    net:add(nn.SpatialConvolution(6, 16, 5, 5))
    net:add(nn.ReLU())
    net:add(nn.SpatialMaxPooling(2, 2, 2, 2))

    net:add(nn.View(16*5*5))
    net:add(nn.Linear(16*5*5, 120))
    net:add(nn.ReLU())
    net:add(nn.Linear(120, 84))
    net:add(nn.ReLU())
    net:add(nn.Linear(84, #classes))
    net:add(nn.LogSoftMax())
    
    parameters, gradParameters = net:getParameters()
    criterion = nn.ClassNLLCriterion()
    confusion = optim.ConfusionMatrix(classes)
end

In [3]:
function normalize(input, n_channels)
    local mean = {}
    local stdev = {}
    
    for channel = 1, n_channels do
        mean[channel] = input.data[{ {}, {channel}, {}, {} }]:mean()
        stdev[channel] = input.data[{ {}, {channel}, {}, {} }]:std()
        
        print('Channel ' .. channel .. ' mean: ' .. mean[channel] .. ' stdev: ' .. stdev[channel])
        
        input.data[{ {}, {channel}, {}, {} }]:add(-mean[channel])
        input.data[{ {}, {channel}, {}, {} }]:div(stdev[channel])
    end
end

In [4]:
function load_data()    
    train = torch.load('mnist-p1b-train.t7')
    test = torch.load('mnist-p1b-test.t7')
    
    n_train = train.data:size()[1]
    n_test = test.data:size()[1]
    
    train.data = train.data:double()
    test.data = test.data:double()
end

In [5]:
function exec_training(obj, n_channels, current_epoch) 
    confusion:zero()
    
    for t = 1, n_train, batch_size do
        local limit = math.min(t + batch_size - 1, n_train)
        
        local limited_batch_size = limit - t + 1
        local inputs = torch.Tensor(limited_batch_size, n_channels, geometry[1], geometry[2])
        local targets = torch.Tensor(limited_batch_size)
        local k = 1
        
        for i = t, limit do
            local input = obj.data[i]:clone()
            local target = obj.label[i]
            
            inputs[k] = input
            targets[k] = target
            k = k + 1
        end
        
        local feval = function(x)
            collectgarbage()
            
            if x ~= parameters then
                parameters:copy(x)
            end
            gradParameters:zero()
            
            local outputs = net:forward(inputs)
            local f = criterion:forward(outputs, targets)
            local df_do = criterion:backward(outputs, targets)
            net:backward(inputs, df_do)
            
            for i = 1, limited_batch_size do
                confusion:add(outputs[i], targets[i])
            end
            
            return f, gradParameters
        end
        
        sgd_state = sgd_state or {
            learningRate = 0.03,
            learningRateDecay = 1e-7,
            momentum = 0.5
        }
        optim.sgd(feval, parameters, sgd_state)
    end
    
    confusion:updateValids()
    return confusion.averageValid
end

In [6]:
function exec_testing(obj, n_channels, current_epoch)
    confusion:zero()
    
    for t = 1, n_test, batch_size do
        local limit = math.min(t + batch_size - 1, n_test)
        
        local limited_batch_size = limit - t + 1
        local inputs = torch.Tensor(limited_batch_size, n_channels, geometry[1], geometry[2])
        local targets = torch.Tensor(limited_batch_size)
        local k = 1
        
        for i = t, limit do
            local input = obj.data[i]:clone()
            local target = obj.label[i]
            
            inputs[k] = input
            targets[k] = target
            k = k + 1
        end
        
        local preds = net:forward(inputs)
        
        for i = 1, limited_batch_size do
            confusion:add(preds[i], targets[i])
        end
    end 
    
    confusion:updateValids()
    return confusion.averageValid
end

In [7]:
setup()
load_data()
normalize(train, 1)
normalize(test, 1)

n_epoch = 32
batch_size = 256
local last_train_conf
local last_test_conf
for epoch = 1, n_epoch do
    local acc_train = exec_training(train, 1, epoch)
    
    if (epoch == n_epoch) then
        last_train_conf = confusion:__tostring__()
    end
    
    local acc_test = exec_testing(test, 1, epoch)
    
    if (epoch == n_epoch) then
        last_test_conf = confusion:__tostring__()
    end
    
    io.write(string.format('Epoch %3d: %.4f%% | %.4f%%\n', epoch, acc_train * 100, acc_test * 100))
end

print(last_train_conf)
print(last_test_conf)

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 63.1956% | 86.4350%


Epoch   2: 92.3765% | 93.5962%


Epoch   3: 95.1587% | 96.0699%


Epoch   4: 96.3743% | 96.9199%


Epoch   5: 97.0129% | 97.1292%


Epoch   6: 97.4392% | 97.4085%


Epoch   7: 97.6867% | 97.6602%


Epoch   8: 97.9385% | 97.9020%


Epoch   9: 98.1291% | 97.9627%


Epoch  10: 98.2964% | 98.1358%


Epoch  11: 98.4244% | 98.1959%


Epoch  12: 98.5664% | 98.2574%


Epoch  13: 98.6806% | 98.3067%


Epoch  14: 98.7761% | 98.3976%


Epoch  15: 98.8579% | 98.4463%


Epoch  16: 98.9098% | 98.5261%


Epoch  17: 98.9797% | 98.5465%


Epoch  18: 99.0350% | 98.6451%


Epoch  19: 99.0952% | 98.6856%


Epoch  20: 99.1404% | 98.6849%


Epoch  21: 99.1847% | 98.7160%


Epoch  22: 99.2302% | 98.7065%


Epoch  23: 99.2753% | 98.7150%


Epoch  24: 99.3147% | 98.7555%


Epoch  25: 99.3561% | 98.7669%


Epoch  26: 99.3915% | 98.7490%


Epoch  27: 99.4496% | 98.7391%


Epoch  28: 99.4955% | 98.7257%


Epoch  29: 99.5299% | 98.6764%


Epoch  30: 99.5589% | 98.7265%


Epoch  31: 99.5971% | 98.7584%


Epoch  32: 99.6036% | 98.7486%
ConfusionMatrix:
[[    5912       1       4       0       1       0       2       0       1       2]   99.814% 	[class: 1]
 [       1    6725       0       0       0       1       3      10       2       0]   99.748% 	[class: 2]
 [       2       3    5941       1       1       1       0       6       3       0]   99.715% 	[class: 3]
 [       0       0       2    6107       0       7       0       4       7       4]   99.609% 	[class: 4]
 [       1       2       0       0    5821       0       4       2       1      11]   99.641% 	[class: 5]
 [       0       1       1       6       1    5395       8       0       5       4]   99.520% 	[class: 6]
 [       4       1       0       0       4       6    5900       0       3       0]   99.696% 	[class: 7]
 [       0       8       4       0       1       0       0    6242       2       8]   99.633% 	[class: 8]
 [       3       6       2       6       2       5       3       2    5813       9]   99.351% 	[class: 9