In [1]:
-- Gloria Budiman
-- EE569 HW4
-- 6528-1836-50
-- 11/25/2016

require 'nn'
require 'optim'

torch.manualSeed(0)
torch.setnumthreads(4)

In [2]:
function setup(threshold) 
    classes = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }
    geometry = { 32, 32 }

    net = nn.Sequential()

    net:add(nn.SpatialConvolution(1, 6, 5, 5))
    
    net:add(nn.AddConstant(threshold))
    net:add(nn.ReLU())
    net:add(nn.AddConstant(-threshold))
    
    net:add(nn.SpatialMaxPooling(2, 2, 2, 2))

    net:add(nn.SpatialConvolution(6, 16, 5, 5))
    
    net:add(nn.AddConstant(threshold))
    net:add(nn.ReLU())
    net:add(nn.AddConstant(-threshold))
    
    net:add(nn.SpatialMaxPooling(2, 2, 2, 2))

    net:add(nn.View(16*5*5))
    net:add(nn.Linear(16*5*5, 120))
    
    net:add(nn.AddConstant(threshold))
    net:add(nn.ReLU())
    net:add(nn.AddConstant(-threshold))
    
    net:add(nn.Linear(120, 84))
    
    net:add(nn.AddConstant(threshold))
    net:add(nn.ReLU())
    net:add(nn.AddConstant(-threshold))
    
    net:add(nn.Linear(84, #classes))
    net:add(nn.LogSoftMax())
    
    parameters, gradParameters = net:getParameters()
    criterion = nn.ClassNLLCriterion()
    confusion = optim.ConfusionMatrix(classes)
end

In [3]:
function normalize(input, n_channels)
    local mean = {}
    local stdev = {}
    
    for channel = 1, n_channels do
        mean[channel] = input.data[{ {}, {channel}, {}, {} }]:mean()
        stdev[channel] = input.data[{ {}, {channel}, {}, {} }]:std()
        
        print('Channel ' .. channel .. ' mean: ' .. mean[channel] .. ' stdev: ' .. stdev[channel])
        
        input.data[{ {}, {channel}, {}, {} }]:add(-mean[channel])
        input.data[{ {}, {channel}, {}, {} }]:div(stdev[channel])
    end
end

In [4]:
function load_data()    
    train = torch.load('mnist-p1b-train.t7')
    test = torch.load('mnist-p1b-test.t7')
    
    n_train = train.data:size()[1]
    n_test = test.data:size()[1]
    
    train.data = train.data:double()
    test.data = test.data:double()
end

In [5]:
function exec_training(obj, n_channels, current_epoch) 
    confusion:zero()
    
    for t = 1, n_train, batch_size do
        local limit = math.min(t + batch_size - 1, n_train)
        
        local limited_batch_size = limit - t + 1
        local inputs = torch.Tensor(limited_batch_size, n_channels, geometry[1], geometry[2])
        local targets = torch.Tensor(limited_batch_size)
        local k = 1
        
        for i = t, limit do
            local input = obj.data[i]:clone()
            local target = obj.label[i]
            
            inputs[k] = input
            targets[k] = target
            k = k + 1
        end
        
        local feval = function(x)
            collectgarbage()
            
            if x ~= parameters then
                parameters:copy(x)
            end
            gradParameters:zero()
            
            local outputs = net:forward(inputs)
            local f = criterion:forward(outputs, targets)
            local df_do = criterion:backward(outputs, targets)
            net:backward(inputs, df_do)
            
            for i = 1, limited_batch_size do
                confusion:add(outputs[i], targets[i])
            end
            
            return f, gradParameters
        end
        
        sgd_state = sgd_state or {
            -- default parameter
        }
        optim.sgd(feval, parameters, sgd_state)
    end
    
    confusion:updateValids()
    return confusion.averageValid
end

In [6]:
function exec_testing(obj, n_channels, current_epoch)
    confusion:zero()
    
    for t = 1, n_test, batch_size do
        local limit = math.min(t + batch_size - 1, n_test)
        
        local limited_batch_size = limit - t + 1
        local inputs = torch.Tensor(limited_batch_size, n_channels, geometry[1], geometry[2])
        local targets = torch.Tensor(limited_batch_size)
        local k = 1
        
        for i = t, limit do
            local input = obj.data[i]:clone()
            local target = obj.label[i]
            
            inputs[k] = input
            targets[k] = target
            k = k + 1
        end
        
        local preds = net:forward(inputs)
        
        for i = 1, limited_batch_size do
            confusion:add(preds[i], targets[i])
        end
    end 
    
    confusion:updateValids()
    return confusion.averageValid
end

In [7]:
function cycle(threshold)
    io.write(string.format('Cycling with threshold %.1f', threshold))
    setup(threshold)
    load_data()
    normalize(train, 1)
    normalize(test, 1)

    n_epoch = 32
    batch_size = 256
    local last_train_conf
    local last_test_conf
    for epoch = 1, n_epoch do
        local acc_train = exec_training(train, 1, epoch)

        if (epoch == n_epoch) then
            last_train_conf = confusion:__tostring__()
        end

        local acc_test = exec_testing(test, 1, epoch)

        if (epoch == n_epoch) then
            last_test_conf = confusion:__tostring__()
        end

        io.write(string.format('Epoch %3d: %.4f%% | %.4f%%\n', epoch, acc_train * 100, acc_test * 100))
    end

    print(last_train_conf)
    print(last_test_conf)
end

In [8]:
for _threshold = -1, 1, 0.1 do
    cycle(_threshold)
end

Cycling with threshold -1.0

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 10.0626% | 10.0000%


Epoch   2: 10.0295% | 10.0000%


Epoch   3: 10.0000% | 10.0000%


Epoch   4: 10.0000% | 10.0000%


Epoch   5: 10.0000% | 10.0000%


Epoch   6: 10.0000% | 10.0000%


Epoch   7: 10.0000% | 10.0000%


Epoch   8: 10.0000% | 10.0000%


Epoch   9: 10.0000% | 10.0000%


Epoch  10: 10.0000% | 10.0000%


Epoch  11: 10.0000% | 10.0000%


Epoch  12: 10.0000% | 10.0000%


Epoch  13: 10.0000% | 10.0000%


Epoch  14: 10.0000% | 10.0000%


Epoch  15: 10.0000% | 10.0000%


Epoch  16: 10.0000% | 10.0000%


Epoch  17: 10.0000% | 10.0000%


Epoch  18: 10.0000% | 10.0000%


Epoch  19: 10.0000% | 10.0000%


Epoch  20: 10.0000% | 10.0000%


Epoch  21: 10.0000% | 10.0000%


Epoch  22: 10.0000% | 10.0000%


Epoch  23: 10.0000% | 10.0000%


Epoch  24: 10.0000% | 10.0000%


Epoch  25: 10.0000% | 10.0000%


Epoch  26: 10.0000% | 10.0000%


Epoch  27: 10.0000% | 10.0000%


Epoch  28: 10.0000% | 10.0000%


Epoch  29: 10.0000% | 10.0000%


Epoch  30: 10.0000% | 10.0000%


Epoch  31: 10.0000% | 10.0000%


Epoch  32: 10.0000% | 10.0000%
ConfusionMatrix:
[[       0    5923       0       0       0       0       0       0       0       0]   0.000% 	[class: 1]
 [       0    6742       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0    5958       0       0       0       0       0       0       0       0]   0.000% 	[class: 3]
 [       0    6131       0       0       0       0       0       0       0       0]   0.000% 	[class: 4]
 [       0    5842       0       0       0       0       0       0       0       0]   0.000% 	[class: 5]
 [       0    5421       0       0       0       0       0       0       0       0]   0.000% 	[class: 6]
 [       0    5918       0       0       0       0       0       0       0       0]   0.000% 	[class: 7]
 [       0    6265       0       0       0       0       0       0       0       0]   0.000% 	[class: 8]
 [       0    5851       0       0       0       0       0       0       0       0]   0.000% 	[class: 9]
 [   

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 9.9132% | 10.0000%


Epoch   2: 10.0000% | 10.0000%


Epoch   3: 10.0000% | 10.0000%


Epoch   4: 10.0000% | 10.0000%


Epoch   5: 10.0000% | 10.0000%


Epoch   6: 10.0000% | 10.0000%


Epoch   7: 10.0000% | 10.0000%


Epoch   8: 10.0000% | 10.0000%


Epoch   9: 10.0000% | 10.0000%


Epoch  10: 10.0000% | 10.0000%


Epoch  11: 10.0000% | 10.0000%


Epoch  12: 10.0000% | 10.0000%


Epoch  13: 10.0000% | 10.0000%


Epoch  14: 10.0000% | 10.0000%


Epoch  15: 10.0000% | 10.0000%


Epoch  16: 10.0000% | 10.0000%


Epoch  17: 10.0000% | 10.0000%


Epoch  18: 10.0000% | 10.0000%


Epoch  19: 10.0000% | 10.0000%


Epoch  20: 10.0000% | 10.0000%


Epoch  21: 10.0000% | 10.0000%


Epoch  22: 10.0000% | 10.0000%


Epoch  23: 10.0000% | 10.0000%


Epoch  24: 10.0000% | 10.0000%


Epoch  25: 10.0000% | 10.0000%


Epoch  26: 10.0000% | 10.0000%


Epoch  27: 10.0000% | 10.0000%


Epoch  28: 10.0000% | 10.0000%


Epoch  29: 10.0000% | 10.0000%


Epoch  30: 10.0000% | 10.0000%


Epoch  31: 10.0000% | 10.0000%


Epoch  32: 10.0000% | 10.0000%
ConfusionMatrix:
[[       0    5923       0       0       0       0       0       0       0       0]   0.000% 	[class: 1]
 [       0    6742       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0    5958       0       0       0       0       0       0       0       0]   0.000% 	[class: 3]
 [       0    6131       0       0       0       0       0       0       0       0]   0.000% 	[class: 4]
 [       0    5842       0       0       0       0       0       0       0       0]   0.000% 	[class: 5]
 [       0    5421       0       0       0       0       0       0       0       0]   0.000% 	[class: 6]
 [       0    5918       0       0       0       0       0       0       0       0]   0.000% 	[class: 7]
 [       0    6265       0       0       0       0       0       0       0       0]   0.000% 	[class: 8]
 [       0    5851       0       0       0       0       0       0       0       0]   0.000% 	[class: 9]
 [   

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 10.0000% | 10.0000%


Epoch   2: 9.9676% | 10.0000%


Epoch   3: 10.0000% | 10.0000%


Epoch   4: 10.0000% | 10.0000%


Epoch   5: 10.0000% | 10.0000%


Epoch   6: 10.0000% | 10.0000%


Epoch   7: 10.0000% | 10.0000%


Epoch   8: 10.0000% | 10.0000%


Epoch   9: 10.0000% | 10.0000%


Epoch  10: 10.0000% | 10.0000%


Epoch  11: 10.0000% | 10.0000%


Epoch  12: 10.0000% | 10.0000%


Epoch  13: 10.0000% | 10.0000%


Epoch  14: 10.0000% | 10.0000%


Epoch  15: 10.0000% | 10.0000%


Epoch  16: 10.0000% | 10.0000%


Epoch  17: 10.0000% | 10.0000%


Epoch  18: 10.0000% | 10.0000%


Epoch  19: 10.0000% | 10.0000%


Epoch  20: 10.0000% | 10.0000%


Epoch  21: 10.0000% | 10.0000%


Epoch  22: 10.0000% | 10.0000%


Epoch  23: 10.0000% | 10.0000%


Epoch  24: 10.0000% | 10.0000%


Epoch  25: 10.0000% | 10.0000%


Epoch  26: 10.0000% | 10.0000%


Epoch  27: 10.0000% | 10.0000%


Epoch  28: 10.0000% | 10.0000%


Epoch  29: 10.0000% | 10.0000%


Epoch  30: 10.0000% | 10.0000%


Epoch  31: 10.0000% | 10.0000%


Epoch  32: 10.0000% | 10.0000%
ConfusionMatrix:
[[       0    5923       0       0       0       0       0       0       0       0]   0.000% 	[class: 1]
 [       0    6742       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0    5958       0       0       0       0       0       0       0       0]   0.000% 	[class: 3]
 [       0    6131       0       0       0       0       0       0       0       0]   0.000% 	[class: 4]
 [       0    5842       0       0       0       0       0       0       0       0]   0.000% 	[class: 5]
 [       0    5421       0       0       0       0       0       0       0       0]   0.000% 	[class: 6]
 [       0    5918       0       0       0       0       0       0       0       0]   0.000% 	[class: 7]
 [       0    6265       0       0       0       0       0       0       0       0]   0.000% 	[class: 8]
 [       0    5851       0       0       0       0       0       0       0       0]   0.000% 	[class: 9]
 [   

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 9.9264% | 10.0000%


Epoch   2: 10.0121% | 10.0000%


Epoch   3: 10.0000% | 10.0000%


Epoch   4: 10.0000% | 10.0000%


Epoch   5: 10.0000% | 10.0000%


Epoch   6: 10.0000% | 10.0000%


Epoch   7: 10.0000% | 10.0000%


Epoch   8: 10.0000% | 10.0000%


Epoch   9: 10.0000% | 10.0000%


Epoch  10: 10.0000% | 10.0000%


Epoch  11: 10.0000% | 10.0000%


Epoch  12: 10.0000% | 10.0000%


Epoch  13: 10.0000% | 10.0000%


Epoch  14: 10.0000% | 10.0000%


Epoch  15: 10.0000% | 10.0000%


Epoch  16: 10.0000% | 10.0000%


Epoch  17: 10.0000% | 10.0000%


Epoch  18: 10.0000% | 10.0000%


Epoch  19: 10.0000% | 10.0000%


Epoch  20: 10.0000% | 10.0000%


Epoch  21: 10.0000% | 10.0000%


Epoch  22: 10.0000% | 10.0000%


Epoch  23: 10.0000% | 10.0000%


Epoch  24: 10.0000% | 10.0000%


Epoch  25: 10.0000% | 10.0000%


Epoch  26: 10.0000% | 10.0000%


Epoch  27: 10.0000% | 10.0000%


Epoch  28: 10.0000% | 10.0000%


Epoch  29: 10.0000% | 10.0000%


Epoch  30: 10.0000% | 10.0000%


Epoch  31: 10.0000% | 10.0000%


Epoch  32: 10.0000% | 10.0000%
ConfusionMatrix:
[[       0    5923       0       0       0       0       0       0       0       0]   0.000% 	[class: 1]
 [       0    6742       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0    5958       0       0       0       0       0       0       0       0]   0.000% 	[class: 3]
 [       0    6131       0       0       0       0       0       0       0       0]   0.000% 	[class: 4]
 [       0    5842       0       0       0       0       0       0       0       0]   0.000% 	[class: 5]
 [       0    5421       0       0       0       0       0       0       0       0]   0.000% 	[class: 6]
 [       0    5918       0       0       0       0       0       0       0       0]   0.000% 	[class: 7]
 [       0    6265       0       0       0       0       0       0       0       0]   0.000% 	[class: 8]
 [       0    5851       0       0       0       0       0       0       0       0]   0.000% 	[class: 9]
 [   

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 10.0000% | 10.0000%


Epoch   2: 10.0000% | 10.0000%


Epoch   3: 10.0000% | 10.0000%


Epoch   4: 10.0000% | 10.0000%


Epoch   5: 10.0000% | 10.0000%


Epoch   6: 10.0000% | 10.0000%


Epoch   7: 10.0000% | 10.0000%


Epoch   8: 10.0000% | 10.0000%


Epoch   9: 10.0000% | 10.0000%


Epoch  10: 10.0000% | 10.0000%


Epoch  11: 10.0000% | 10.0000%


Epoch  12: 10.0000% | 10.0000%


Epoch  13: 10.0000% | 10.0000%


Epoch  14: 10.0000% | 10.0000%


Epoch  15: 10.0000% | 10.0000%


Epoch  16: 10.0000% | 10.0000%


Epoch  17: 10.0000% | 10.0000%


Epoch  18: 10.0000% | 10.0000%


Epoch  19: 10.0000% | 10.0000%


Epoch  20: 10.0000% | 10.0000%


Epoch  21: 10.0000% | 10.0000%


Epoch  22: 10.0000% | 10.0000%


Epoch  23: 10.0000% | 10.0000%


Epoch  24: 10.0000% | 10.0000%


Epoch  25: 10.0000% | 10.0000%


Epoch  26: 10.0000% | 10.0000%


Epoch  27: 10.0000% | 10.0000%


Epoch  28: 10.0000% | 10.0000%


Epoch  29: 10.0000% | 10.0000%


Epoch  30: 10.0000% | 10.0000%


Epoch  31: 10.0000% | 10.0000%


Epoch  32: 10.0000% | 10.0000%
ConfusionMatrix:
[[       0    5923       0       0       0       0       0       0       0       0]   0.000% 	[class: 1]
 [       0    6742       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0    5958       0       0       0       0       0       0       0       0]   0.000% 	[class: 3]
 [       0    6131       0       0       0       0       0       0       0       0]   0.000% 	[class: 4]
 [       0    5842       0       0       0       0       0       0       0       0]   0.000% 	[class: 5]
 [       0    5421       0       0       0       0       0       0       0       0]   0.000% 	[class: 6]
 [       0    5918       0       0       0       0       0       0       0       0]   0.000% 	[class: 7]
 [       0    6265       0       0       0       0       0       0       0       0]   0.000% 	[class: 8]
 [       0    5851       0       0       0       0       0       0       0       0]   0.000% 	[class: 9]
 [   

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 10.0000% | 10.0000%


Epoch   2: 10.0000% | 10.0000%


Epoch   3: 10.0000% | 10.0584%


Epoch   4: 10.8806% | 10.0000%


Epoch   5: 9.9725% | 10.0000%


Epoch   6: 10.0000% | 10.0000%


Epoch   7: 10.0000% | 10.0000%


Epoch   8: 10.0000% | 10.0000%


Epoch   9: 10.0000% | 10.0000%


Epoch  10: 10.0000% | 10.0000%


Epoch  11: 10.0000% | 10.0000%


Epoch  12: 10.0000% | 10.0000%


Epoch  13: 10.0000% | 10.0000%


Epoch  14: 10.0000% | 10.0000%


Epoch  15: 10.0000% | 10.0000%


Epoch  16: 10.0000% | 10.0000%


Epoch  17: 10.0000% | 10.0000%


Epoch  18: 10.0000% | 10.0000%


Epoch  19: 10.0000% | 10.0000%


Epoch  20: 10.0000% | 10.0000%


Epoch  21: 10.0000% | 10.0000%


Epoch  22: 10.0000% | 10.0000%


Epoch  23: 10.0000% | 10.0000%


Epoch  24: 10.0000% | 10.0000%


Epoch  25: 10.0000% | 10.0000%


Epoch  26: 10.0000% | 10.0000%


Epoch  27: 10.0000% | 10.0000%


Epoch  28: 10.0000% | 10.0000%


Epoch  29: 10.0000% | 10.0000%


Epoch  30: 10.0000% | 10.0000%


Epoch  31: 10.0000% | 10.0000%


Epoch  32: 10.0000% | 10.0000%
ConfusionMatrix:
[[       0    5923       0       0       0       0       0       0       0       0]   0.000% 	[class: 1]
 [       0    6742       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0    5958       0       0       0       0       0       0       0       0]   0.000% 	[class: 3]
 [       0    6131       0       0       0       0       0       0       0       0]   0.000% 	[class: 4]
 [       0    5842       0       0       0       0       0       0       0       0]   0.000% 	[class: 5]
 [       0    5421       0       0       0       0       0       0       0       0]   0.000% 	[class: 6]
 [       0    5918       0       0       0       0       0       0       0       0]   0.000% 	[class: 7]
 [       0    6265       0       0       0       0       0       0       0       0]   0.000% 	[class: 8]
 [       0    5851       0       0       0       0       0       0       0       0]   0.000% 	[class: 9]
 [   

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 10.0000% | 10.0000%


Epoch   2: 10.0000% | 10.0000%


Epoch   3: 10.0000% | 10.0000%


Epoch   4: 10.0000% | 10.0000%


Epoch   5: 10.1854% | 10.0000%


Epoch   6: 10.0000% | 10.0000%


Epoch   7: 10.0000% | 10.0000%


Epoch   8: 10.0000% | 10.0000%


Epoch   9: 10.0000% | 10.0000%


Epoch  10: 10.0000% | 10.0000%


Epoch  11: 10.0000% | 10.0000%


Epoch  12: 10.0000% | 10.0000%


Epoch  13: 10.0000% | 10.0000%


Epoch  14: 10.0000% | 10.0000%


Epoch  15: 10.0000% | 10.0000%


Epoch  16: 10.0000% | 10.0000%


Epoch  17: 10.0000% | 10.0000%


Epoch  18: 10.0000% | 10.0000%


Epoch  19: 10.0000% | 10.0000%


Epoch  20: 10.0000% | 10.0000%


Epoch  21: 10.0000% | 10.0000%


Epoch  22: 10.0000% | 10.0000%


Epoch  23: 10.0000% | 10.0000%


Epoch  24: 10.0000% | 10.0000%


Epoch  25: 10.0000% | 10.0000%


Epoch  26: 10.0000% | 10.0000%


Epoch  27: 10.0000% | 10.0000%


Epoch  28: 10.0000% | 10.0000%


Epoch  29: 10.0000% | 10.0000%


Epoch  30: 10.0000% | 10.0000%


Epoch  31: 10.0000% | 10.0000%


Epoch  32: 10.0000% | 10.0000%


ConfusionMatrix:
[[       0    5923       0       0       0       0       0       0       0       0]   0.000% 	[class: 1]
 [       0    6742       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0    5958       0       0       0       0       0       0       0       0]   0.000% 	[class: 3]
 [       0    6131       0       0       0       0       0       0       0       0]   0.000% 	[class: 4]
 [       0    5842       0       0       0       0       0       0       0       0]   0.000% 	[class: 5]
 [       0    5421       0       0       0       0       0       0       0       0]   0.000% 	[class: 6]
 [       0    5918       0       0       0       0       0       0       0       0]   0.000% 	[class: 7]
 [       0    6265       0       0       0       0       0       0       0       0]   0.000% 	[class: 8]
 [       0    5851       0       0       0       0       0       0       0       0]   0.000% 	[class: 9]
 [       0    5949       0       0  

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 10.0000% | 10.0000%


Epoch   2: 10.6187% | 15.3027%


Epoch   3: 10.1642% | 10.0000%


Epoch   4: 10.0000% | 10.0000%


Epoch   5: 10.0000% | 10.0000%


Epoch   6: 10.0000% | 10.0000%


Epoch   7: 10.0000% | 10.0000%


Epoch   8: 10.0000% | 10.0000%


Epoch   9: 10.0000% | 10.0000%


Epoch  10: 10.0000% | 10.0000%


Epoch  11: 10.0000% | 10.0000%


Epoch  12: 10.0000% | 10.0000%


Epoch  13: 10.0000% | 10.0000%


Epoch  14: 10.0000% | 10.0000%


Epoch  15: 10.0000% | 10.0000%


Epoch  16: 10.0000% | 10.0000%


Epoch  17: 10.0000% | 10.0000%


Epoch  18: 10.0000% | 10.0000%


Epoch  19: 10.0000% | 10.0000%


Epoch  20: 10.0000% | 10.0000%


Epoch  21: 10.0000% | 10.0000%


Epoch  22: 10.0000% | 10.0000%


Epoch  23: 10.0000% | 10.0000%


Epoch  24: 10.0000% | 10.0000%


Epoch  25: 10.0000% | 10.0000%


Epoch  26: 10.0000% | 10.0000%


Epoch  27: 10.0000% | 10.0000%


Epoch  28: 10.0000% | 10.0000%


Epoch  29: 10.0000% | 10.0000%


Epoch  30: 10.0000% | 10.0000%


Epoch  31: 10.0000% | 10.0000%


Epoch  32: 10.0000% | 10.0000%
ConfusionMatrix:
[[       0    5923       0       0       0       0       0       0       0       0]   0.000% 	[class: 1]
 [       0    6742       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0    5958       0       0       0       0       0       0       0       0]   0.000% 	[class: 3]
 [       0    6131       0       0       0       0       0       0       0       0]   0.000% 	[class: 4]
 [       0    5842       0       0       0       0       0       0       0       0]   0.000% 	[class: 5]
 [       0    5421       0       0       0       0       0       0       0       0]   0.000% 	[class: 6]
 [       0    5918       0       0       0       0       0       0       0       0]   0.000% 	[class: 7]
 [       0    6265       0       0       0       0       0       0       0       0]   0.000% 	[class: 8]
 [       0    5851       0       0       0       0       0       0       0       0]   0.000% 	[class: 9]
 [   

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 10.0000% | 10.0000%


Epoch   2: 10.0000% | 10.0000%


Epoch   3: 10.0000% | 10.0000%


Epoch   4: 10.0000% | 10.0000%


Epoch   5: 10.0000% | 10.0000%


Epoch   6: 10.0000% | 10.0000%


Epoch   7: 10.0000% | 10.0000%


Epoch   8: 10.1796% | 10.6696%


Epoch   9: 16.0478% | 18.3799%


Epoch  10: 20.0207% | 21.3888%


Epoch  11: 22.2637% | 23.9633%


Epoch  12: 25.2096% | 27.8900%


Epoch  13: 30.3511% | 34.1069%


Epoch  14: 36.9206% | 41.0709%


Epoch  15: 43.6700% | 47.1945%


Epoch  16: 50.4036% | 57.7997%


Epoch  17: 60.2608% | 65.4530%


Epoch  18: 65.7673% | 70.3143%


Epoch  19: 70.1853% | 74.6680%


Epoch  20: 74.6956% | 78.0860%


Epoch  21: 78.1629% | 80.3976%


Epoch  22: 80.5831% | 82.4630%


Epoch  23: 82.6194% | 84.0930%


Epoch  24: 84.0614% | 85.4733%


Epoch  25: 85.2390% | 86.4935%


Epoch  26: 86.1195% | 87.2731%


Epoch  27: 86.8966% | 87.7709%


Epoch  28: 87.5132% | 88.4301%


Epoch  29: 88.0776% | 88.8885%


Epoch  30: 88.5041% | 89.2390%


Epoch  31: 88.9435% | 89.5722%


Epoch  32: 89.2737% | 89.8986%
ConfusionMatrix:
[[    5664       0      20      27      11      52      37       5     101       6]   95.627% 	[class: 1]
 [       0    6495      49      43       4      39       9      11      81      11]   96.336% 	[class: 2]
 [      47      53    5275      87     123      17     108     104     118      26]   88.536% 	[class: 3]
 [      44      61     152    5252       4     236      35      94     158      95]   85.663% 	[class: 4]
 [       8      18      65       1    5181       8     115      12      31     403]   88.685% 	[class: 5]
 [     103      69      37     235      73    4561     143      16     130      54]   84.136% 	[class: 6]
 [      55      54      59       1      73     115    5519       4      36       2]   93.258% 	[class: 7]
 [      25      79     114      11      60      27       0    5637      19     293]   89.976% 	[class: 8]
 [      31     166      55     214      39     127      68      16    5024     111]   85.866% 	[class: 9

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 10.0000% | 10.0000%


Epoch   2: 10.0000% | 10.0000%


Epoch   3: 10.0000% | 10.0000%


Epoch   4: 10.0000% | 10.0000%


Epoch   5: 10.0124% | 10.0325%


Epoch   6: 10.6093% | 11.4405%


Epoch   7: 13.7612% | 15.7534%


Epoch   8: 16.8186% | 17.0598%


Epoch   9: 16.5385% | 15.9296%


Epoch  10: 15.1299% | 14.4951%


Epoch  11: 13.8140% | 13.4436%


Epoch  12: 12.9342% | 12.7043%


Epoch  13: 12.3610% | 12.2763%


Epoch  14: 11.9811% | 12.0428%


Epoch  15: 11.8071% | 11.9163%


Epoch  16: 11.8329% | 11.9783%


Epoch  17: 12.0955% | 12.5516%


Epoch  18: 13.1966% | 14.6359%


Epoch  19: 16.4916% | 19.4188%


Epoch  20: 21.2961% | 23.6718%


Epoch  21: 24.8177% | 26.2736%


Epoch  22: 26.4387% | 27.0467%


Epoch  23: 27.3719% | 27.8351%


Epoch  24: 28.1691% | 28.5702%


Epoch  25: 28.7069% | 29.2789%


Epoch  26: 29.6417% | 30.3226%


Epoch  27: 30.9557% | 31.8861%


Epoch  28: 32.6200% | 34.3194%


Epoch  29: 35.7105% | 38.5665%


Epoch  30: 40.8474% | 44.7863%


Epoch  31: 47.5537% | 51.3544%


Epoch  32: 53.7317% | 59.7701%
ConfusionMatrix:
[[    5456      31       0      79      58       0     223       5      42      29]   92.115% 	[class: 1]
 [       0    6599       3      70       2       0      57       7       2       2]   97.879% 	[class: 2]
 [     488     890    1258    1522     132       0    1234     102     260      72]   21.114% 	[class: 3]
 [     418     961       5    4230      56       0     303     109      31      18]   68.994% 	[class: 4]
 [     711     329       0       5    3257       0     169     358      17     996]   55.751% 	[class: 5]
 [    2731     621       1     521     475       2     520     203      59     288]   0.037% 	[class: 6]
 [     982     420       6      49      21       0    4359      30      14      37]   73.657% 	[class: 7]
 [     350    1055      22      74     193       1      13    4396       8     153]   70.168% 	[class: 8]
 [     347    1750      40     964     120       0     627     307    1418     278]   24.235% 	[class: 9]

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 13.0386% | 14.2661%


Epoch   2: 16.3623% | 17.1936%


Epoch   3: 18.7997% | 18.9726%


Epoch   4: 19.9917% | 19.9123%


Epoch   5: 20.5758% | 20.9604%


Epoch   6: 21.6615% | 22.9089%


Epoch   7: 24.6353% | 27.8180%


Epoch   8: 32.7687% | 40.4150%


Epoch   9: 45.8867% | 51.8891%


Epoch  10: 55.4766% | 60.5348%


Epoch  11: 64.2432% | 68.5851%


Epoch  12: 70.0235% | 73.2453%


Epoch  13: 74.4384% | 77.1956%


Epoch  14: 77.6663% | 79.6031%


Epoch  15: 80.0201% | 81.8160%


Epoch  16: 82.0172% | 83.5027%


Epoch  17: 83.5315% | 84.8297%


Epoch  18: 84.6320% | 85.6455%


Epoch  19: 85.6490% | 86.4608%


Epoch  20: 86.4431% | 87.3075%


Epoch  21: 87.1547% | 87.8045%


Epoch  22: 87.8161% | 88.4320%


Epoch  23: 88.4131% | 89.0183%


Epoch  24: 88.9312% | 89.6087%


Epoch  25: 89.3381% | 90.0552%


Epoch  26: 89.7880% | 90.4133%


Epoch  27: 90.1949% | 90.7631%


Epoch  28: 90.5099% | 91.0894%


Epoch  29: 90.8063% | 91.3804%


Epoch  30: 91.1191% | 91.6596%


Epoch  31: 91.3948% | 91.8826%


Epoch  32: 91.6530% | 92.1405%
ConfusionMatrix:
[[    5707       4      20       9       9      40      57       7      60      10]   96.353% 	[class: 1]
 [       0    6530      56      29       8      33       7      14      54      11]   96.856% 	[class: 2]
 [      39      39    5389      90     111      22      77      81      87      23]   90.450% 	[class: 3]
 [      25      50     115    5452       6     199      28      77     115      64]   88.925% 	[class: 4]
 [       4      24      44       2    5341       4      95      15      30     283]   91.424% 	[class: 5]
 [      68      35      37     235      78    4719     111       8      89      41]   87.050% 	[class: 6]
 [      43      40      48       1      68      94    5599       1      23       1]   94.610% 	[class: 7]
 [      15      57      85      14      63       8       1    5820       8     194]   92.897% 	[class: 8]
 [      31     123      48     127      39     121      39      10    5201     112]   88.891% 	[class: 9

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 14.9667% | 15.8958%


Epoch   2: 17.2557% | 18.0545%


Epoch   3: 20.1498% | 21.8882%


Epoch   4: 24.6939% | 29.0826%


Epoch   5: 35.6876% | 43.8763%


Epoch   6: 49.9504% | 55.5663%


Epoch   7: 57.7514% | 59.4732%


Epoch   8: 59.1182% | 59.8353%


Epoch   9: 60.3874% | 62.2062%


Epoch  10: 65.4150% | 69.6677%


Epoch  11: 73.6564% | 77.4460%


Epoch  12: 79.1103% | 81.3087%


Epoch  13: 82.0835% | 83.6457%


Epoch  14: 84.2136% | 85.4448%


Epoch  15: 85.7238% | 86.7773%


Epoch  16: 86.8320% | 87.7898%


Epoch  17: 87.6816% | 88.6213%


Epoch  18: 88.3105% | 89.0825%


Epoch  19: 88.9261% | 89.5830%


Epoch  20: 89.3897% | 89.9757%


Epoch  21: 89.8161% | 90.3541%


Epoch  22: 90.1824% | 90.6308%


Epoch  23: 90.5008% | 91.1416%


Epoch  24: 90.8111% | 91.4110%


Epoch  25: 91.0673% | 91.7081%


Epoch  26: 91.3090% | 92.0204%


Epoch  27: 91.5661% | 92.3234%


Epoch  28: 91.8032% | 92.5681%


Epoch  29: 92.0027% | 92.8447%


Epoch  30: 92.2320% | 93.0270%


Epoch  31: 92.4295% | 93.1399%


Epoch  32: 92.6403% | 93.3039%
ConfusionMatrix:
[[    5724       4      24      14       5      39      34      12      51      16]   96.640% 	[class: 1]
 [       3    6555      42      25       8      28       6      13      53       9]   97.226% 	[class: 2]
 [      45      37    5422      80      99      14      49      85     106      21]   91.004% 	[class: 3]
 [      20      35     102    5529       3     199      11      66     115      51]   90.181% 	[class: 4]
 [       5      21      48       3    5407       3      53      15      27     260]   92.554% 	[class: 5]
 [      58      38      14     146      45    4883     112      17      68      40]   90.076% 	[class: 6]
 [      41      29      25       1      45      83    5674       0      19       1]   95.877% 	[class: 7]
 [      13      43      94      10      56       8       0    5859      13     169]   93.520% 	[class: 8]
 [      33     110      57     138      30      89      28      11    5258      97]   89.865% 	[class: 9

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 16.7748% | 19.3955%


Epoch   2: 19.7624% | 21.2605%


Epoch   3: 24.1819% | 27.1766%


Epoch   4: 32.2058% | 37.0847%


Epoch   5: 41.3280% | 45.6765%


Epoch   6: 48.5246% | 52.4489%


Epoch   7: 53.6079% | 57.4672%


Epoch   8: 57.5243% | 61.4843%


Epoch   9: 63.2261% | 68.6049%


Epoch  10: 71.2301% | 76.0912%


Epoch  11: 77.4171% | 80.7166%


Epoch  12: 81.2252% | 83.7176%


Epoch  13: 83.8151% | 85.5981%


Epoch  14: 85.6297% | 87.0381%


Epoch  15: 86.8283% | 88.1327%


Epoch  16: 87.6627% | 88.7812%


Epoch  17: 88.3310% | 89.2722%


Epoch  18: 88.8898% | 89.7138%


Epoch  19: 89.3742% | 90.0417%


Epoch  20: 89.7768% | 90.4037%


Epoch  21: 90.1430% | 90.7712%


Epoch  22: 90.4843% | 91.1020%


Epoch  23: 90.7471% | 91.4697%


Epoch  24: 90.9997% | 91.7381%


Epoch  25: 91.2513% | 91.9021%


Epoch  26: 91.4579% | 92.1228%


Epoch  27: 91.6768% | 92.2518%


Epoch  28: 91.9047% | 92.5132%


Epoch  29: 92.1272% | 92.7254%


Epoch  30: 92.2875% | 92.9223%


Epoch  31: 92.4436% | 93.0115%


Epoch  32: 92.5764% | 93.1842%
ConfusionMatrix:
[[    5749       0      14      18       8      28      32      10      51      13]   97.062% 	[class: 1]
 [       1    6554      46      23       9      35       6      11      45      12]   97.212% 	[class: 2]
 [      32      31    5405      67     116      19      69      92     114      13]   90.718% 	[class: 3]
 [      27      40      94    5518       4     187      11      55     137      58]   90.002% 	[class: 4]
 [       7      25      49       5    5365       2      58      12      33     286]   91.835% 	[class: 5]
 [      46      46      29     143      45    4898     101      10      72      31]   90.352% 	[class: 6]
 [      35      19      20       8      43      95    5672       2      24       0]   95.843% 	[class: 7]
 [      15      42      90      18      48      10       1    5845      11     185]   93.296% 	[class: 8]
 [      25      84      66     163      19      85      36       9    5259     105]   89.882% 	[class: 9

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 9.0859% | 10.0666%


Epoch   2: 11.4644% | 13.8143%


Epoch   3: 18.6179% | 25.9413%


Epoch   4: 34.7672% | 43.9726%


Epoch   5: 48.6048% | 54.9154%


Epoch   6: 57.0017% | 61.8061%


Epoch   7: 61.2285% | 63.5669%


Epoch   8: 62.1051% | 63.0904%


Epoch   9: 61.8134% | 62.9712%


Epoch  10: 62.9966% | 66.6536%


Epoch  11: 70.2765% | 75.8689%


Epoch  12: 78.0267% | 81.8547%


Epoch  13: 82.0473% | 84.7236%


Epoch  14: 84.4606% | 86.4845%


Epoch  15: 86.1661% | 87.8167%


Epoch  16: 87.3513% | 88.7053%


Epoch  17: 88.3375% | 89.5110%


Epoch  18: 89.0649% | 90.0945%


Epoch  19: 89.6641% | 90.6071%


Epoch  20: 90.1053% | 91.0335%


Epoch  21: 90.5131% | 91.5685%


Epoch  22: 90.9180% | 91.8167%


Epoch  23: 91.2584% | 92.0884%


Epoch  24: 91.5295% | 92.2986%


Epoch  25: 91.7513% | 92.5434%


Epoch  26: 92.0067% | 92.7394%


Epoch  27: 92.2381% | 92.9059%


Epoch  28: 92.4409% | 93.1285%


Epoch  29: 92.6323% | 93.3598%


Epoch  30: 92.8043% | 93.5928%


Epoch  31: 92.9902% | 93.7453%


Epoch  32: 93.1625% | 93.9132%
ConfusionMatrix:
[[    5759       2      15       7       8      23      43       7      51       8]   97.231% 	[class: 1]
 [       0    6552      53      20       8      23      10      12      53      11]   97.182% 	[class: 2]
 [      31      39    5443      78     100      16      50      89      94      18]   91.356% 	[class: 3]
 [      20      32     106    5612       2     130      12      64      99      54]   91.535% 	[class: 4]
 [       6      20      50       2    5420       2      65      23      23     231]   92.776% 	[class: 5]
 [      24      39      23     126      28    4979      67       5      91      39]   91.847% 	[class: 6]
 [      41      37      33       1      41      69    5673       0      22       1]   95.860% 	[class: 7]
 [      11      33      91      13      54       6       1    5849       7     200]   93.360% 	[class: 8]
 [      18      99      57     134      29      80      25      12    5293     104]   90.463% 	[class: 9

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 18.2653% | 28.8975%


Epoch   2: 34.8874% | 42.3527%


Epoch   3: 48.7906% | 54.6346%


Epoch   4: 57.6400% | 60.5193%


Epoch   5: 61.2030% | 62.5283%


Epoch   6: 62.9422% | 64.9693%


Epoch   7: 67.5929% | 71.5160%


Epoch   8: 74.8891% | 78.8984%


Epoch   9: 80.1887% | 82.7477%


Epoch  10: 83.0064% | 84.6751%


Epoch  11: 84.7615% | 86.3593%


Epoch  12: 86.1328% | 87.3682%


Epoch  13: 87.1350% | 88.3369%


Epoch  14: 87.8982% | 88.8696%


Epoch  15: 88.4800% | 89.4424%


Epoch  16: 88.9953% | 89.7873%


Epoch  17: 89.4212% | 90.2304%


Epoch  18: 89.8277% | 90.5815%


Epoch  19: 90.1374% | 90.8584%


Epoch  20: 90.4316% | 91.0361%


Epoch  21: 90.7269% | 91.3526%


Epoch  22: 91.0156% | 91.6074%


Epoch  23: 91.2727% | 91.8544%


Epoch  24: 91.4900% | 92.0826%


Epoch  25: 91.7101% | 92.3233%


Epoch  26: 91.9479% | 92.5065%


Epoch  27: 92.2109% | 92.6601%


Epoch  28: 92.4071% | 92.9262%


Epoch  29: 92.5980% | 93.0911%


Epoch  30: 92.8004% | 93.2562%


Epoch  31: 92.9595% | 93.4718%


Epoch  32: 93.1286% | 93.6478%
ConfusionMatrix:
[[    5742       3      22      16       7      34      45       6      39       9]   96.944% 	[class: 1]
 [       1    6577      40      23       7      16      10      14      46       8]   97.553% 	[class: 2]
 [      40      27    5429      63     100      15      73      86     104      21]   91.121% 	[class: 3]
 [      18      33      96    5574       3     160      20      55     113      59]   90.915% 	[class: 4]
 [       5      22      44       2    5415       2      52      13      33     254]   92.691% 	[class: 5]
 [      55      33      17     123      31    4939      85       8      88      42]   91.109% 	[class: 6]
 [      42      18      30       1      53      73    5678       0      20       3]   95.945% 	[class: 7]
 [      16      27      70      16      55      11       0    5896      11     163]   94.110% 	[class: 8]
 [      27      93      46     128      20      82      42      15    5293     105]   90.463% 	[class: 9

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 13.5878% | 19.8779%


Epoch   2: 27.3243% | 35.7718%


Epoch   3: 48.6442% | 56.9882%


Epoch   4: 62.7266% | 67.1227%


Epoch   5: 69.6136% | 72.7767%


Epoch   6: 73.4245% | 75.8486%


Epoch   7: 76.3078% | 79.1036%


Epoch   8: 80.0693% | 83.1790%


Epoch   9: 83.1626% | 85.4155%


Epoch  10: 85.1979% | 86.9583%


Epoch  11: 86.6584% | 88.2507%


Epoch  12: 87.7412% | 89.0465%


Epoch  13: 88.5213% | 89.6615%


Epoch  14: 89.1770% | 90.1785%


Epoch  15: 89.8041% | 90.6793%


Epoch  16: 90.3175% | 91.0531%


Epoch  17: 90.7083% | 91.3650%


Epoch  18: 91.0646% | 91.7756%


Epoch  19: 91.4334% | 92.1609%


Epoch  20: 91.7269% | 92.4767%


Epoch  21: 92.0121% | 92.7040%


Epoch  22: 92.2562% | 92.9177%


Epoch  23: 92.4774% | 93.1138%


Epoch  24: 92.7008% | 93.2663%


Epoch  25: 92.9409% | 93.4016%


Epoch  26: 93.1606% | 93.6664%


Epoch  27: 93.3289% | 93.8603%


Epoch  28: 93.5198% | 93.9814%


Epoch  29: 93.6978% | 94.1563%


Epoch  30: 93.8482% | 94.3570%


Epoch  31: 93.9808% | 94.4774%


Epoch  32: 94.1321% | 94.6882%
ConfusionMatrix:
[[    5761       3      25       4       4      24      37       8      42      15]   97.265% 	[class: 1]
 [       1    6580      51      17      10      14      13      13      32      11]   97.597% 	[class: 2]
 [      36      25    5511      65      78      15      46      75      88      19]   92.497% 	[class: 3]
 [      18      21      92    5656       1     136      11      53      91      52]   92.252% 	[class: 4]
 [       4      14      34       2    5505       1      57      12      25     188]   94.231% 	[class: 5]
 [      34      25      15      99      16    5056      79       7      54      36]   93.267% 	[class: 6]
 [      38      21      21       0      39      66    5703       2      28       0]   96.367% 	[class: 7]
 [      12      21      76      20      43       7       0    5922      14     150]   94.525% 	[class: 8]
 [      22      90      50      98      22      85      26      11    5351      96]   91.454% 	[class: 9

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 20.7264% | 27.5556%


Epoch   2: 36.7903% | 44.9545%


Epoch   3: 49.3494% | 54.1178%


Epoch   4: 55.0165% | 58.4735%


Epoch   5: 59.1379% | 62.3361%


Epoch   6: 64.0032% | 68.1812%


Epoch   7: 70.7240% | 75.1952%


Epoch   8: 76.9319% | 80.1663%


Epoch   9: 80.6612% | 83.2335%


Epoch  10: 83.3510% | 85.4474%


Epoch  11: 85.3012% | 87.1398%


Epoch  12: 86.6591% | 88.0810%


Epoch  13: 87.5824% | 88.8324%


Epoch  14: 88.2953% | 89.4594%


Epoch  15: 88.8690% | 90.0338%


Epoch  16: 89.4193% | 90.4884%


Epoch  17: 89.8993% | 90.7318%


Epoch  18: 90.2792% | 91.1111%


Epoch  19: 90.5969% | 91.4518%


Epoch  20: 90.9161% | 91.7555%


Epoch  21: 91.2241% | 91.9687%


Epoch  22: 91.5065% | 92.1944%


Epoch  23: 91.7894% | 92.4633%


Epoch  24: 92.0089% | 92.6976%


Epoch  25: 92.2536% | 92.8437%


Epoch  26: 92.4417% | 92.9755%


Epoch  27: 92.6441% | 93.2463%


Epoch  28: 92.8236% | 93.3880%


Epoch  29: 93.0016% | 93.5379%


Epoch  30: 93.1623% | 93.7835%


Epoch  31: 93.3005% | 93.9044%


Epoch  32: 93.4847% | 94.0654%
ConfusionMatrix:
[[    5755       1      18      11       6      29      41       8      44      10]   97.164% 	[class: 1]
 [       0    6554      54      26      10      22       7      14      44      11]   97.212% 	[class: 2]
 [      41      31    5514      66      82      16      37      72      89      10]   92.548% 	[class: 3]
 [      20      39      94    5586       2     148      10      60     119      53]   91.111% 	[class: 4]
 [       6      18      35       4    5458       5      54      15      24     223]   93.427% 	[class: 5]
 [      47      36      22     118      43    4977      75       9      52      42]   91.810% 	[class: 6]
 [      28      30      16       1      39      62    5718       2      21       1]   96.620% 	[class: 7]
 [      27      32      90      18      56      10       0    5850      15     167]   93.376% 	[class: 8]
 [      20      92      63     116      29      69      44      10    5326      82]   91.027% 	[class: 9

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 13.3015% | 23.2099%


Epoch   2: 33.9785% | 45.8012%


Epoch   3: 53.8702% | 61.2258%


Epoch   4: 63.2890% | 67.0691%


Epoch   5: 68.1213% | 71.7581%


Epoch   6: 73.5072% | 77.4981%


Epoch   7: 78.7607% | 81.5097%


Epoch   8: 82.0757% | 83.9161%


Epoch   9: 84.3076% | 85.7737%


Epoch  10: 85.8498% | 87.0067%


Epoch  11: 86.9856% | 88.0125%


Epoch  12: 87.8434% | 88.8253%


Epoch  13: 88.5652% | 89.5713%


Epoch  14: 89.1961% | 90.0695%


Epoch  15: 89.7317% | 90.5640%


Epoch  16: 90.1970% | 90.9185%


Epoch  17: 90.5853% | 91.2705%


Epoch  18: 90.9091% | 91.6003%


Epoch  19: 91.2674% | 91.9030%


Epoch  20: 91.6095% | 92.1553%


Epoch  21: 91.9059% | 92.4878%


Epoch  22: 92.1549% | 92.7267%


Epoch  23: 92.3999% | 93.0041%


Epoch  24: 92.6263% | 93.2984%


Epoch  25: 92.8650% | 93.5022%


Epoch  26: 93.0551% | 93.6479%


Epoch  27: 93.2708% | 93.7678%


Epoch  28: 93.4412% | 93.9112%


Epoch  29: 93.6326% | 94.0669%


Epoch  30: 93.7911% | 94.2268%


Epoch  31: 93.9461% | 94.4689%


Epoch  32: 94.0699% | 94.6322%
ConfusionMatrix:
[[    5744       3      19       7       8      25      47       4      62       4]   96.978% 	[class: 1]
 [       0    6580      44      30       7      21       6       8      40       6]   97.597% 	[class: 2]
 [      40      33    5545      75      56      11      44      58      80      16]   93.068% 	[class: 3]
 [      22      29     102    5618       3     152       6      67      87      45]   91.633% 	[class: 4]
 [       5      16      31       3    5479       2      64       8      24     210]   93.786% 	[class: 5]
 [      39      25      15     114      24    5055      65       7      43      34]   93.248% 	[class: 6]
 [      48      21      36       0      39      50    5707       0      17       0]   96.435% 	[class: 7]
 [      14      31      49      20      38       7       0    5938       8     160]   94.781% 	[class: 8]
 [      14      79      40     114      26      69      43      15    5370      81]   91.779% 	[class: 9

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 14.0482% | 24.1726%


Epoch   2: 32.2212% | 43.5079%


Epoch   3: 47.3479% | 53.2097%


Epoch   4: 52.8581% | 55.5639%


Epoch   5: 55.1858% | 58.8556%


Epoch   6: 60.7136% | 66.1930%


Epoch   7: 68.5278% | 73.0385%


Epoch   8: 75.5343% | 79.4818%


Epoch   9: 80.5453% | 83.2161%


Epoch  10: 83.5803% | 85.8257%


Epoch  11: 85.4942% | 87.2199%


Epoch  12: 86.7857% | 88.2774%


Epoch  13: 87.7562% | 89.2032%


Epoch  14: 88.5559% | 89.8330%


Epoch  15: 89.2052% | 90.3776%


Epoch  16: 89.7092% | 90.8076%


Epoch  17: 90.1230% | 91.2664%


Epoch  18: 90.5162% | 91.5182%


Epoch  19: 90.8808% | 91.7727%


Epoch  20: 91.1531% | 92.0589%


Epoch  21: 91.4432% | 92.2545%


Epoch  22: 91.6939% | 92.4868%


Epoch  23: 91.9164% | 92.6617%


Epoch  24: 92.1435% | 92.8688%


Epoch  25: 92.3733% | 93.0790%


Epoch  26: 92.5770% | 93.2927%


Epoch  27: 92.7874% | 93.4242%


Epoch  28: 92.9797% | 93.6044%


Epoch  29: 93.1426% | 93.7247%


Epoch  30: 93.2908% | 93.8907%


Epoch  31: 93.4199% | 94.0199%


Epoch  32: 93.5803% | 94.1333%
ConfusionMatrix:
[[    5754       2      19      17       5      20      42       8      45      11]   97.147% 	[class: 1]
 [       1    6585      45      24      10      12      12      10      34       9]   97.671% 	[class: 2]
 [      34      28    5468      89      85      11      56      77      85      25]   91.776% 	[class: 3]
 [      21      29     120    5621       3     107      14      60     106      50]   91.682% 	[class: 4]
 [       5      18      26       1    5469       2      59      13      27     222]   93.615% 	[class: 5]
 [      34      32      25      88      22    5008      85       9      70      48]   92.381% 	[class: 6]
 [      35      21      28       0      54      67    5694       0      18       1]   96.215% 	[class: 7]
 [      19      26      88      12      35      11       0    5862      12     200]   93.567% 	[class: 8]
 [      23      62      58     133      25      81      36      14    5328      91]   91.061% 	[class: 9

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 9.3618% | 9.9535%


Epoch   2: 11.6769% | 14.1302%


Epoch   3: 19.5419% | 26.2190%


Epoch   4: 34.6779% | 42.2611%


Epoch   5: 49.3616% | 53.6748%


Epoch   6: 59.3881% | 62.0701%


Epoch   7: 64.6808% | 67.3826%


Epoch   8: 69.9164% | 74.5086%


Epoch   9: 77.1755% | 81.1424%


Epoch  10: 82.2572% | 84.8755%


Epoch  11: 85.1242% | 86.9819%


Epoch  12: 86.7937% | 88.4941%


Epoch  13: 88.0699% | 89.6803%


Epoch  14: 88.9782% | 90.4496%


Epoch  15: 89.6799% | 91.0611%


Epoch  16: 90.2549% | 91.4411%


Epoch  17: 90.7253% | 91.6851%


Epoch  18: 91.1226% | 92.1933%


Epoch  19: 91.4343% | 92.5768%


Epoch  20: 91.8070% | 92.9304%


Epoch  21: 92.1265% | 93.1957%


Epoch  22: 92.3721% | 93.4286%


Epoch  23: 92.5880% | 93.5923%


Epoch  24: 92.8607% | 93.8169%


Epoch  25: 93.0694% | 94.0351%


Epoch  26: 93.2741% | 94.2052%


Epoch  27: 93.4605% | 94.4427%


Epoch  28: 93.6598% | 94.5951%


Epoch  29: 93.8125% | 94.7210%


Epoch  30: 94.0040% | 94.8506%


Epoch  31: 94.1710% | 94.9410%


Epoch  32: 94.3170% | 95.0597%
ConfusionMatrix:
[[    5764       1      15      10       7      15      36      10      56       9]   97.316% 	[class: 1]
 [       0    6570      50      22      12      17       8      13      43       7]   97.449% 	[class: 2]
 [      36      36    5530      68      50      11      42      73      89      23]   92.816% 	[class: 3]
 [      22      23      87    5679       2     107      12      46     108      45]   92.628% 	[class: 4]
 [       6      24      28       3    5530       2      35      16      15     183]   94.659% 	[class: 5]
 [      37      33      18      78      19    5078      57       9      45      47]   93.673% 	[class: 6]
 [      38      22      15       0      37      59    5723       0      24       0]   96.705% 	[class: 7]
 [      16      29      74      17      38       6       0    5932      11     142]   94.685% 	[class: 8]
 [      14      74      65     106      20      65      28       9    5370     100]   91.779% 	[class: 9

Channel 1 mean: 25.509416422526 stdev: 70.180423838273	


Channel 1 mean: 25.87140625 stdev: 70.739298703524	


Epoch   1: 10.4814% | 12.4484%


Epoch   2: 19.3988% | 29.0566%


Epoch   3: 39.5024% | 49.6270%


Epoch   4: 54.4803% | 60.3361%


Epoch   5: 61.3966% | 66.5518%


Epoch   6: 69.0520% | 74.8452%


Epoch   7: 76.5115% | 80.2949%


Epoch   8: 81.0037% | 83.6242%


Epoch   9: 83.6956% | 85.9952%


Epoch  10: 85.3921% | 87.2089%


Epoch  11: 86.5362% | 88.2856%


Epoch  12: 87.5338% | 88.8501%


Epoch  13: 88.2861% | 89.6327%


Epoch  14: 88.8929% | 90.0299%


Epoch  15: 89.3678% | 90.3385%


Epoch  16: 89.7805% | 90.6190%


Epoch  17: 90.1460% | 91.0047%


Epoch  18: 90.4398% | 91.2803%


Epoch  19: 90.6685% | 91.5832%


Epoch  20: 90.9426% | 91.8064%


Epoch  21: 91.2186% | 92.0603%


Epoch  22: 91.4680% | 92.2817%


Epoch  23: 91.6909% | 92.4552%


Epoch  24: 91.9070% | 92.6283%


Epoch  25: 92.1245% | 92.7820%


Epoch  26: 92.2955% | 92.9979%


Epoch  27: 92.4595% | 93.2178%


Epoch  28: 92.6080% | 93.3937%


Epoch  29: 92.7675% | 93.5589%


Epoch  30: 92.9395% | 93.6719%


Epoch  31: 93.0954% | 93.8348%


Epoch  32: 93.2432% | 93.9328%
ConfusionMatrix:
[[    5743       2      17      16       6      32      39       9      43      16]   96.961% 	[class: 1]
 [       0    6559      44      19       7      22       6      15      60      10]   97.286% 	[class: 2]
 [      37      45    5502      67      81      11      53      89      63      10]   92.346% 	[class: 3]
 [      32      38      95    5574       1     149      21      63     103      55]   90.915% 	[class: 4]
 [       4      21      44       3    5429       2      64      10      22     243]   92.931% 	[class: 5]
 [      56      38      16     106      34    4952      98      14      56      51]   91.348% 	[class: 6]
 [      45      24      29       3      42      86    5670       0      18       1]   95.809% 	[class: 7]
 [      16      42      75      12      43      12       0    5887       8     170]   93.966% 	[class: 8]
 [      23      79      39     148      23      91      40      12    5307      89]   90.702% 	[class: 9